Repository 2024-Team-Techeer-Salon/Moitda-Backend, pull requests merged in 2024-05, with the labels that each got.

#10 chore : spring 세팅 변경 및 swagger 적용
  build.gradle
  compose.yaml
  src/main/java/com/techeersalon/moitda/MoitdaApplication.java
  src/main/java/com/techeersalon/moitda/controller/MeettingsController.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: 🧭 Chore

#12 [ feat] 소셜 로그인 추가
  .gitignore
  build.gradle
  compose.yaml
  src/main/java/com/techeersalon/moitda/domain/user/controller/UserController.java
  src/main/java/com/techeersalon/moitda/domain/user/dto/request/SignUpReq.java
  src/main/java/com/techeersalon/moitda/domain/user/entity/Gender.java
  src/main/java/com/techeersalon/moitda/domain/user/entity/Role.java
  src/main/java/com/techeersalon/moitda/domain/user/entity/SocialType.java
  src/main/java/com/techeersalon/moitda/domain/user/entity/User.java
  src/main/java/com/techeersalon/moitda/domain/user/repository/UserRepository.java
  src/main/java/com/techeersalon/moitda/domain/user/service/UserService.java
  src/main/java/com/techeersalon/moitda/global/common/BaseEntity.java
  src/main/java/com/techeersalon/moitda/global/config/SecurityConfig.java
  src/main/java/com/techeersalon/moitda/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/techeersalon/moitda/global/jwt/Service/JwtService.java
  src/main/java/com/techeersalon/moitda/global/oauth/CustomOAuth2User.java
  src/main/java/com/techeersalon/moitda/global/oauth/GoogleOAuth2UserInfo.java
  src/main/java/com/techeersalon/moitda/global/oauth/KakaoOAuth2UserInfo.java
  src/main/java/com/techeersalon/moitda/global/oauth/NaverOAuth2UserInfo.java
  src/main/java/com/techeersalon/moitda/global/oauth/OAuth2LoginFailureHandler.java
  src/main/java/com/techeersalon/moitda/global/oauth/OAuth2LoginSuccessHandler.java
  src/main/java/com/techeersalon/moitda/global/oauth/OAuth2UserInfo.java
  src/main/java/com/techeersalon/moitda/global/oauth/OAuthAttributes.java
  src/main/java/com/techeersalon/moitda/global/oauth/Service/CustomOAuth2UserService.java
  src/main/resources/application.yml
Labels: 🚀 Feat

#22 [feat] 모임 신청, 승인 api / 참가자 entity 등 개발
  src/main/java/com/techeersalon/moitda/domain/meetings/controller/MeetingsController.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/request/CreateMeetingParticipantRequest.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/request/CreateMeetingRequest.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/response/CreateMeetingResponse.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/response/GetMeetingDetailResponse.java
  src/main/java/com/techeersalon/moitda/domain/meetings/entity/Category.java
  src/main/java/com/techeersalon/moitda/domain/meetings/entity/Meeting.java
  src/main/java/com/techeersalon/moitda/domain/meetings/entity/MeetingParticipant.java
  src/main/java/com/techeersalon/moitda/domain/meetings/repository/MeetingParticipantRepository.java
  src/main/java/com/techeersalon/moitda/domain/meetings/repository/MeetingRepository.java
  src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java
  src/main/java/com/techeersalon/moitda/domain/user/service/UserService.java
  src/main/java/com/techeersalon/moitda/global/common/BaseEntity.java
  src/main/resources/application.yml
Labels: 🚀 Feat

#24 [feat] 모임 생성시 host도 참가자 생성 / 모임 조회 api에 참가자 List 전송
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/request/CreateMeetingRequest.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/response/GetMeetingDetailResponse.java
  src/main/java/com/techeersalon/moitda/domain/meetings/entity/MeetingParticipant.java
  src/main/java/com/techeersalon/moitda/domain/meetings/repository/MeetingParticipantRepository.java
  src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java
Labels: 🚀 Feat

#26 [fix] webConfig 추가 및 meeting api 중 모임 생성 기능 수정
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/request/CreateMeetingRequest.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/response/GetMeetingDetailResponse.java
  src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java
  src/main/java/com/techeersalon/moitda/domain/user/service/UserService.java
  src/main/java/com/techeersalon/moitda/global/config/SecurityConfig.java
  src/main/java/com/techeersalon/moitda/global/config/WebConfig.java
Labels: 🏷 Fix

#28 [feat] 최신 미팅 리스트 api
  src/main/java/com/techeersalon/moitda/config/StartConfig.java
  src/main/java/com/techeersalon/moitda/domain/meetings/controller/MeetingsController.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/request/CreateMeetingRequest.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/response/GetLatestMeetingListResponse.java
  src/main/java/com/techeersalon/moitda/domain/meetings/entity/Meeting.java
  src/main/java/com/techeersalon/moitda/domain/meetings/repository/MeetingRepository.java
  src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java
Labels: 🚀 Feat

#35 [fix] 모임 신청, 상세조회, 모임 신청 완료 & cors관련 수정
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/MeetingParticipantDto.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/request/CreateMeetingRequest.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/response/GetMeetingDetailResponse.java
  src/main/java/com/techeersalon/moitda/domain/meetings/entity/Category.java
  src/main/java/com/techeersalon/moitda/domain/meetings/entity/Meeting.java
  src/main/java/com/techeersalon/moitda/domain/meetings/entity/MeetingParticipant.java
  src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java
  src/main/java/com/techeersalon/moitda/domain/user/dto/mapper/UserMapper.java
  src/main/java/com/techeersalon/moitda/domain/user/dto/response/UserProfileRes.java
  src/main/java/com/techeersalon/moitda/global/common/BaseEntity.java
  src/main/java/com/techeersalon/moitda/global/config/SecurityConfig.java
  src/main/java/com/techeersalon/moitda/global/config/WebConfig.java
Labels: 🏷 Fix

#37 [feat] 미팅 취소, 미팅 수정 api 구현
  src/main/java/com/techeersalon/moitda/domain/meetings/controller/MeetingsController.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/request/ChangeMeetingInfoRequest.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/response/GetMeetingDetailResponse.java
  src/main/java/com/techeersalon/moitda/domain/meetings/entity/Meeting.java
  src/main/java/com/techeersalon/moitda/domain/meetings/entity/MeetingParticipant.java
  src/main/java/com/techeersalon/moitda/domain/meetings/repository/MeetingParticipantRepository.java
  src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java
Labels: 🚀 Feat

#41 [feat] delete api 삭제 방식 변경
  src/main/java/com/techeersalon/moitda/chat/service/ChatRoomService.java
  src/main/java/com/techeersalon/moitda/config/StartConfig.java
  src/main/java/com/techeersalon/moitda/domain/meetings/entity/Meeting.java
  src/main/java/com/techeersalon/moitda/domain/meetings/entity/MeetingParticipant.java
  src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java
  src/main/java/com/techeersalon/moitda/domain/user/entity/User.java
  src/main/java/com/techeersalon/moitda/global/common/BaseEntity.java
  src/main/java/com/techeersalon/moitda/global/config/SecurityConfig.java
Labels: 🚀 Feat

#48 [feat] 기능구현 완료
  src/main/java/com/techeersalon/moitda/domain/chat/service/ChatMessageService.java
  src/main/java/com/techeersalon/moitda/domain/meetings/controller/MeetingsController.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/mapper/MeetingParticipantMapper.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/request/ChangeMeetingInfoReq.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/request/CreateMeetingReq.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/response/CreateMeetingRes.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/response/GetLatestMeetingListRes.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/response/GetMeetingDetailRes.java
  src/main/java/com/techeersalon/moitda/domain/meetings/entity/Meeting.java
  src/main/java/com/techeersalon/moitda/domain/meetings/entity/MeetingParticipant.java
  src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java
  src/main/java/com/techeersalon/moitda/global/config/StartConfig.java
Labels: 🚀 Feat

#53 [Refactor] user 응답처리 수정
  src/main/java/com/techeersalon/moitda/domain/user/controller/UserController.java
  src/main/java/com/techeersalon/moitda/domain/user/entity/User.java
  src/main/java/com/techeersalon/moitda/domain/user/exception/UserNotFoundException.java
  src/main/java/com/techeersalon/moitda/domain/user/service/UserService.java
  src/main/java/com/techeersalon/moitda/global/common/SuccessCode.java
  src/main/java/com/techeersalon/moitda/global/common/SuccessResponse.java
  src/main/java/com/techeersalon/moitda/global/error/ErrorResponse.java
  src/main/java/com/techeersalon/moitda/global/jwt/Service/JwtService.java
Labels: 🧹 Refactor

#59 [feat] s3이미지 폼데이터 형식
  build.gradle
  src/main/java/com/techeersalon/moitda/domain/meetings/controller/MeetingsController.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/request/ChangeMeetingInfoReq.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/request/CreateMeetingReq.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/response/GetLatestMeetingListRes.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/response/GetMeetingDetailRes.java
  src/main/java/com/techeersalon/moitda/domain/meetings/entity/Meeting.java
  src/main/java/com/techeersalon/moitda/domain/meetings/entity/MeetingImage.java
  src/main/java/com/techeersalon/moitda/domain/meetings/repository/MeetingImageRepository.java
  src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java
  src/main/java/com/techeersalon/moitda/domain/user/controller/UserController.java
  src/main/java/com/techeersalon/moitda/domain/user/dto/mapper/UserMapper.java
  src/main/java/com/techeersalon/moitda/domain/user/dto/request/UpdateUserReq.java
  src/main/java/com/techeersalon/moitda/domain/user/dto/response/UserMeetingRecordRes.java
  src/main/java/com/techeersalon/moitda/domain/user/entity/User.java
  src/main/java/com/techeersalon/moitda/domain/user/exception/UserAlreadyRegisteredException.java
  src/main/java/com/techeersalon/moitda/domain/user/service/UserService.java
  src/main/java/com/techeersalon/moitda/global/config/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/techeersalon/moitda/global/config/S3Config.java
  src/main/java/com/techeersalon/moitda/global/error/ErrorCode.java
  src/main/java/com/techeersalon/moitda/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/techeersalon/moitda/global/oauth/OAuth2LoginSuccessHandler.java
  src/main/java/com/techeersalon/moitda/global/s3/exception/S3Exception.java
Labels: 🚀 Feat

#60 [fix] 프론트 요청사항 수정
  src/main/java/com/techeersalon/moitda/domain/meetings/controller/MeetingsController.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/mapper/MeetingParticipantListMapper.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/mapper/MeetingParticipantMapper.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/request/ChangeMeetingInfoReq.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/request/CreateMeetingReq.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/response/GetLatestMeetingListRes.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/response/GetMeetingDetailRes.java
  src/main/java/com/techeersalon/moitda/domain/meetings/entity/Meeting.java
  src/main/java/com/techeersalon/moitda/domain/meetings/entity/MeetingImage.java
  src/main/java/com/techeersalon/moitda/domain/meetings/entity/MeetingParticipant.java
  src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java
  src/main/java/com/techeersalon/moitda/domain/user/service/UserService.java
  src/main/java/com/techeersalon/moitda/global/config/InitializeDummyDataConfig.java
  src/main/java/com/techeersalon/moitda/global/config/StartConfig.java
Labels: 🏷 Fix

#63 [fix] put api, list 0번째 이미지만 나오게 하기, 유저 히스토리 수정
  src/main/java/com/techeersalon/moitda/domain/meetings/controller/MeetingsController.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/response/GetLatestMeetingListRes.java
  src/main/java/com/techeersalon/moitda/domain/meetings/entity/Meeting.java
  src/main/java/com/techeersalon/moitda/domain/meetings/repository/MeetingRepository.java
  src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java
  src/main/java/com/techeersalon/moitda/domain/user/controller/UserController.java
Labels: 🏷 Fix

#66 [feat] 카테고리 검색 기능 추가, 더미 데이터 생성 수정
  src/main/java/com/techeersalon/moitda/domain/meetings/controller/MeetingsController.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/request/CreateMeetingReq.java
  src/main/java/com/techeersalon/moitda/domain/meetings/repository/MeetingRepository.java
  src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java
  src/main/java/com/techeersalon/moitda/global/config/InitializeDummyDataConfig.java
Labels: 🚀 Feat

#67 [feat] 후기 기능 구현
  src/main/java/com/techeersalon/moitda/domain/meetings/controller/MeetingsController.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/request/CreateReviewReq.java
  src/main/java/com/techeersalon/moitda/domain/meetings/exception/review/InvalidRatingScoreException.java
  src/main/java/com/techeersalon/moitda/domain/meetings/exception/review/MeetingNotEndedException.java
  src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java
  src/main/java/com/techeersalon/moitda/domain/user/controller/UserController.java
  src/main/java/com/techeersalon/moitda/domain/user/entity/User.java
  src/main/java/com/techeersalon/moitda/global/common/SuccessCode.java
  src/main/java/com/techeersalon/moitda/global/error/ErrorCode.java
  src/main/java/com/techeersalon/moitda/global/oauth/OAuth2LoginSuccessHandler.java
Labels: 🚀 Feat

#72 [feat] 모임 종료, 삭제 수정
  src/main/java/com/techeersalon/moitda/domain/meetings/controller/MeetingsController.java
  src/main/java/com/techeersalon/moitda/global/common/SuccessCode.java
  src/main/java/com/techeersalon/moitda/global/config/InitializeDummyDataConfig.java
Labels: 🚀 Feat

#74 [fix] meeting api dto 수정
  src/main/java/com/techeersalon/moitda/domain/meetings/controller/MeetingsController.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/mapper/MeetingParticipantListMapper.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/response/GetMeetingDetailRes.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/response/GetParticipantListRes.java
  src/main/java/com/techeersalon/moitda/domain/meetings/entity/Meeting.java
  src/main/java/com/techeersalon/moitda/domain/meetings/exception/participant/MeetingParticipantNotFoundException.java
  src/main/java/com/techeersalon/moitda/domain/meetings/repository/MeetingParticipantRepository.java
  src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java
  src/main/java/com/techeersalon/moitda/domain/user/service/UserService.java
  src/main/java/com/techeersalon/moitda/global/common/SuccessCode.java
Labels: 🏷 Fix

#76 Feat/#75 검색 기능 구현
  src/main/java/com/techeersalon/moitda/domain/meetings/controller/MeetingsController.java
  src/main/java/com/techeersalon/moitda/domain/meetings/repository/MeetingRepository.java
  src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java
  src/main/java/com/techeersalon/moitda/domain/user/service/UserService.java
  src/main/java/com/techeersalon/moitda/global/common/SuccessCode.java
Labels: 🚀 Feat

#78 [feat] 사용자 정보 조회 구현
  src/main/java/com/techeersalon/moitda/domain/meetings/controller/MeetingsController.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/mapper/MeetingParticipantListMapper.java
  src/main/java/com/techeersalon/moitda/domain/meetings/repository/MeetingParticipantRepository.java
  src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java
  src/main/java/com/techeersalon/moitda/domain/user/controller/UserController.java
  src/main/java/com/techeersalon/moitda/domain/user/service/UserService.java
  src/main/java/com/techeersalon/moitda/global/oauth/OAuthAttributes.java
Labels: 🚀 Feat

#80 [fix] s3 로직 수정
  src/main/java/com/techeersalon/moitda/domain/meetings/controller/MeetingsController.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/response/GetMeetingDetailRes.java
  src/main/java/com/techeersalon/moitda/domain/meetings/repository/MeetingParticipantRepository.java
  src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java
  src/main/java/com/techeersalon/moitda/domain/user/controller/UserController.java
  src/main/java/com/techeersalon/moitda/domain/user/service/UserService.java
Labels: 🏷 Fix

#82 [fix]MeetingService findMeetingById메서드 수정
  src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java
Labels: 🏷 Fix

#84 [fix] meeting service 수정
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/response/GetMeetingDetailRes.java
  src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java
Labels: 🏷 Fix

#85 [feat] 거리가 가까운 순으로 검색 및 모임 조회
  build.gradle
  src/main/java/com/techeersalon/moitda/domain/meetings/controller/MeetingsController.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/mapper/PointMapper.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/request/ChangeMeetingInfoReq.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/request/CreateMeetingReq.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/response/GetLatestMeetingListRes.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/response/GetSearchPageRes.java
  src/main/java/com/techeersalon/moitda/domain/meetings/entity/Meeting.java
  src/main/java/com/techeersalon/moitda/domain/meetings/repository/MeetingRepository.java
  src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java
  src/main/java/com/techeersalon/moitda/domain/user/controller/UserController.java
  src/main/java/com/techeersalon/moitda/global/config/InitializeDummyDataConfig.java
Labels: 🚀 Feat

#87 [feat] end_time이 null인 데이터만 조회 가능, keyword검색
  src/main/java/com/techeersalon/moitda/domain/meetings/controller/MeetingsController.java
  src/main/java/com/techeersalon/moitda/domain/meetings/repository/MeetingRepository.java
  src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java
Labels: 🚀 Feat

#94 [feat] 기본 거리 모임 리스 조회 1.5km로 제한
  src/main/java/com/techeersalon/moitda/domain/meetings/controller/MeetingsController.java
  src/main/java/com/techeersalon/moitda/domain/meetings/repository/MeetingRepository.java
  src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java
Labels: 🚀 Feat
