Repository 2024-Team-Techeer-Salon/Moitda-Backend, pull requests merged in 2024-06, with the labels that each got.

#91 Feat/#89 nginx 추가
  build.gradle
  compose.yaml
  nginx/Dockerfile
  nginx/nginx.conf
  src/main/java/com/techeersalon/moitda/domain/meetings/repository/MeetingRepository.java
  src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java
  src/main/java/com/techeersalon/moitda/domain/user/controller/UserController.java
  src/main/java/com/techeersalon/moitda/domain/user/dto/mapper/UserMapper.java
  src/main/java/com/techeersalon/moitda/domain/user/dto/response/UserIdRes.java
  src/main/java/com/techeersalon/moitda/domain/user/service/UserService.java
Labels: 🚀 Feat

#96 [chore] elk 완료
  .gitignore
  Dockerfile
  build.gradle
  compose.yaml
  compose_dev.yaml
  compose_logging.yaml
  logging/elasticsearch/config/elasticsearch.yml
  logging/filebeat/filebeat.yml
  logging/logstash/config/logstash.yml
  logging/logstash/pipeline/pipeline.conf
  src/main/resources/logback-spring.xml
Labels: 🧭 Chore

#100 [chore] local 환경애서 정상작동
  build.gradle
  src/main/java/com/techeersalon/moitda/MoitdaApplication.java
  src/main/resources/logback-spring.xml.bak
Labels: 🧭 Chore

#101 [feat] 1.5km이내 있는 모임 데이터 마감이 가까운 순으로 리스트 조회
  src/main/java/com/techeersalon/moitda/domain/meetings/controller/MeetingsController.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/response/GetLatestMeetingListRes.java
  src/main/java/com/techeersalon/moitda/domain/meetings/repository/MeetingRepository.java
  src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java
Labels: 🚀 Feat

#104 [feat] Docker Wait for it 적용 및 nginx 프론트엔드 연결
  Dockerfile
  compose.yaml
  nginx/Dockerfile
  nginx/nginx.conf
  src/main/java/com/techeersalon/moitda/domain/meetings/repository/MeetingRepository.java
  wait-for-it.sh
Labels: 🚀 Feat

#106 fix : 타 사용자 정보 조회인지 구분
  src/main/java/com/techeersalon/moitda/domain/user/dto/mapper/UserMapper.java
  src/main/java/com/techeersalon/moitda/domain/user/dto/response/UserProfileRes.java
  src/main/java/com/techeersalon/moitda/domain/user/service/UserService.java
Labels: 🏷 Fix

#108 [fix] 토큰 관련 로직 수정
  src/main/java/com/techeersalon/moitda/domain/user/controller/UserController.java
  src/main/java/com/techeersalon/moitda/domain/user/dto/mapper/UserMapper.java
  src/main/java/com/techeersalon/moitda/domain/user/dto/request/UserTokenReq.java
  src/main/java/com/techeersalon/moitda/domain/user/exception/UnAuthorizedAccessException.java
  src/main/java/com/techeersalon/moitda/domain/user/service/UserService.java
  src/main/java/com/techeersalon/moitda/global/common/SuccessCode.java
  src/main/java/com/techeersalon/moitda/global/config/SecurityConfig.java
  src/main/java/com/techeersalon/moitda/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/techeersalon/moitda/global/jwt/JwtToken.java
  src/main/java/com/techeersalon/moitda/global/jwt/Service/JwtService.java
  src/main/java/com/techeersalon/moitda/global/jwt/exception/JwtAccessDeniedHandler.java
  src/main/java/com/techeersalon/moitda/global/jwt/exception/JwtAuthenticationEntryPoint.java
  src/main/resources/static/index.html
  src/main/resources/static/signup.html
Labels: 🚀 Feat, 🏷 Fix

#111 [fix] userService s3 관련 수정
  src/main/java/com/techeersalon/moitda/domain/user/service/UserService.java
Labels: 🏷 Fix

#113 feat : 미팅 리스트 조회 response 값 수정
  .DS_Store
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/response/GetLatestMeetingListRes.java
Labels: 🚀 Feat

#116 [test] userService 테스트코드 작성
  src/main/java/com/techeersalon/moitda/domain/user/dto/request/SignUpReq.java
  src/main/java/com/techeersalon/moitda/domain/user/dto/request/UpdateUserReq.java
  src/main/java/com/techeersalon/moitda/domain/user/entity/User.java
  src/main/java/com/techeersalon/moitda/domain/user/service/UserService.java
  src/test/java/com/techeersalon/moitda/domain/user/service/UserServiceTest.java
Labels: 📁 Test

#120 [feat] meetingService 수정
  src/main/java/com/techeersalon/moitda/domain/meetings/controller/MeetingsController.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/mapper/MeetingParticipantListMapper.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/mapper/MeetingParticipantMapper.java
  src/main/java/com/techeersalon/moitda/domain/meetings/dto/request/CreateMeetingReq.java
  src/main/java/com/techeersalon/moitda/domain/meetings/entity/MeetingParticipant.java
  src/main/java/com/techeersalon/moitda/domain/meetings/exception/review/AlreadyReviewedException.java
  src/main/java/com/techeersalon/moitda/domain/meetings/repository/MeetingParticipantRepository.java
  src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java
  src/main/java/com/techeersalon/moitda/global/common/SuccessCode.java
  src/main/java/com/techeersalon/moitda/global/error/ErrorCode.java
Labels: 🚀 Feat

#122 [fix] nginx 수정, docker-compose 수정
  compose.yaml
  nginx/nginx.conf
  src/main/java/com/techeersalon/moitda/global/config/SecurityConfig.java
  src/main/java/com/techeersalon/moitda/global/oauth/OAuth2LoginSuccessHandler.java
Labels: 🏷 Fix

#124 [fix] 채팅 버그 수정
  src/main/java/com/techeersalon/moitda/domain/chat/dto/mapper/ChatMapper.java
  src/main/java/com/techeersalon/moitda/domain/user/dto/mapper/UserMapper.java
  src/main/java/com/techeersalon/moitda/domain/user/service/UserService.java
Labels: 🏷 Fix

#118 [chore] 사전 준비 완료
  .gitignore
  Dockerfile
  build.gradle
  compose.yaml
  src/main/java/com/techeersalon/moitda/MoitdaApplication.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
  src/main/resources/logback-spring.xml.bak
Labels: 🧭 Chore

#129 [chore] ci 완성 및 로컬 환경에서 테스트 완료
  .github/workflows/CI.yml
Labels: 🧭 Chore
